import Head from 'next/head'
import Link from 'next/link'
import { Navbar } from '@/components/Navbar'
import styles from '@/styles/Home.module.css'

export default function ContactPage()  {
  return (
    <>
      <Head>
        <title>Contact - Daniel Lagunas </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={styles.main}>
          <h1>Contact Page</h1>

          <h1 className={styles.title}>
            Ir a <Link href={'/'}>Home</Link>
          </h1>
          <p className={styles.main}>
            Get started by editing{' '};
            <code className={styles.code}>pages/contact.tsx</code>
          </p>

      </main>
    </>
  )
}
