import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function aboutPage()  {
  return (
    <>
      <Head>
        <title>About - Daniel Lagunas </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <h1 className={styles.title}>
            Ir a <a href="/">Home</a>
          </h1>
          <p className={styles.main}>
            Get started by editing{' '};
            <code className={styles.code}>pages/about.tsx</code>
          </p>

      </main>
    </>
  )
}
