import Head from 'next/head'

import styles from '@/styles/Home.module.css'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Home - Daniel lagunas </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <h1 className={styles.title}>
            {/* Ir a <a href="/about">About</a> */}
            Ir a <Link href={'/about'}>About</Link>
          </h1>
          <p className={styles.main}>
            Get started by editing{' '};
            <code className={styles.code}>pages/index.tsx</code>
          </p>
      </main>
    </>
  )
}
